import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { formatMinutes } from "@/lib/timesheets/meta";
import { formatMoneyCents } from "@/lib/contracts/meta";
import type { ClientReport } from "./report";

const PAGE_W = 595.28;
const PAGE_H = 841.89;
const M = 50;

export async function buildTimesheetReportPdf(r: ClientReport): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const gray = rgb(0.42, 0.42, 0.46);
  const black = rgb(0.1, 0.1, 0.12);

  let page = doc.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - M;

  const draw = (s: string, x: number, yy: number, size: number, f = font, color = black) =>
    page.drawText(s, { x, y: yy, size, font: f, color });
  const rightX = PAGE_W - M;
  const truncate = (s: string, maxW: number, size: number): string => {
    if (font.widthOfTextAtSize(s, size) <= maxW) return s;
    let t = s;
    while (t.length > 1 && font.widthOfTextAtSize(t + "…", size) > maxW) t = t.slice(0, -1);
    return t + "…";
  };

  // Header
  draw(r.companyName, M, y, 16, bold);
  draw("Timesheet report", M, y - 18, 10, font, gray);
  draw(r.clientName, rightX - bold.widthOfTextAtSize(r.clientName, 11), y, 11, bold);
  draw(r.periodLabel, rightX - font.widthOfTextAtSize(r.periodLabel, 10), y - 16, 10, font, gray);
  y -= 50;

  // Summary
  draw(`Total time: ${formatMinutes(r.totalMinutes)}`, M, y, 10, bold);
  draw(`Billable: ${formatMinutes(r.billableMinutes)}`, M + 170, y, 10, bold);
  draw(`Amount: ${formatMoneyCents(r.totalAmountCents)}`, M + 320, y, 10, bold);
  y -= 26;

  // Table columns
  const cDate = M;
  const cWho = M + 70;
  const cWork = M + 185;
  const cDur = rightX - 130;
  const drawHeader = (yy: number) => {
    draw("Date", cDate, yy, 8, bold, gray);
    draw("Who", cWho, yy, 8, bold, gray);
    draw("Work", cWork, yy, 8, bold, gray);
    draw("Duration", cDur, yy, 8, bold, gray);
    draw("Amount", rightX - bold.widthOfTextAtSize("Amount", 8), yy, 8, bold, gray);
  };
  drawHeader(y);
  y -= 5;
  page.drawLine({ start: { x: M, y }, end: { x: rightX, y }, thickness: 0.5, color: gray });
  y -= 15;

  const size = 9;
  for (const row of r.rows) {
    if (y < M + 50) {
      page = doc.addPage([PAGE_W, PAGE_H]);
      y = PAGE_H - M;
      drawHeader(y);
      y -= 20;
    }
    draw(row.date.toLocaleDateString(), cDate, y, size);
    draw(truncate(row.who, cWork - cWho - 8, size), cWho, y, size);
    const work = row.work + (row.billable ? "" : " (non-billable)");
    draw(truncate(work, cDur - cWork - 12, size), cWork, y, size);
    draw(formatMinutes(row.minutes), cDur, y, size);
    const amt = formatMoneyCents(row.amountCents);
    draw(amt, rightX - font.widthOfTextAtSize(amt, size), y, size);
    y -= 16;
  }

  // Totals
  page.drawLine({ start: { x: M, y: y + 8 }, end: { x: rightX, y: y + 8 }, thickness: 0.5, color: gray });
  draw("Total", cWork, y - 4, 9, bold);
  draw(formatMinutes(r.totalMinutes), cDur, y - 4, 9, bold);
  const tot = formatMoneyCents(r.totalAmountCents);
  draw(tot, rightX - bold.widthOfTextAtSize(tot, 9), y - 4, 9, bold);

  draw(
    `Generated by ${r.companyName} — amounts exclude taxes. Rejected entries are excluded.`,
    M,
    M - 24,
    7,
    font,
    gray,
  );

  return doc.save();
}
