export const PERMISSIONS = {
  "users.read": { label: "View users", group: "Users" },
  "users.manage": { label: "Manage users", group: "Users" },
  "roles.read": { label: "View roles", group: "Roles" },
  "roles.manage": { label: "Manage roles", group: "Roles" },
  "clients.read": { label: "View clients", group: "Clients" },
  "clients.manage": { label: "Manage clients", group: "Clients" },
  "clients.assign": { label: "Assign client technician", group: "Clients" },
  "settings.manage": { label: "Manage settings", group: "Settings" },
  "tickets.read": { label: "View tickets", group: "Tickets" },
  "tickets.manage": { label: "Manage tickets", group: "Tickets" },
  "tickets.assign": { label: "Assign tickets", group: "Tickets" },
  "projects.read": { label: "View projects", group: "Projects" },
  "projects.manage": { label: "Manage projects", group: "Projects" },
  "projects.assign": { label: "Assign project tasks", group: "Projects" },
  "visits.read": { label: "View planning", group: "Planning" },
  "visits.manage": { label: "Manage visits", group: "Planning" },
  "visits.assign": { label: "Assign visits", group: "Planning" },
  "timesheets.read": { label: "Log & view own time", group: "Timesheets" },
  "timesheets.read.all": { label: "View all timesheets", group: "Timesheets" },
  "timesheets.approve": { label: "Approve timesheets", group: "Timesheets" },
  "contracts.read": { label: "View contracts", group: "Contracts" },
  "contracts.manage": { label: "Manage contracts", group: "Contracts" },
  "knowledge.read": { label: "View knowledge base", group: "Knowledge" },
  "knowledge.manage": { label: "Manage knowledge base", group: "Knowledge" },
  "devices.read": { label: "View devices", group: "Devices" },
  "devices.manage": { label: "Manage devices", group: "Devices" },
  "subscriptions.read": { label: "View subscriptions", group: "Subscriptions" },
  "subscriptions.manage": { label: "Manage subscriptions", group: "Subscriptions" },
  "audit.read": { label: "View audit log", group: "Settings" },
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;

export const PERMISSION_KEYS = Object.keys(PERMISSIONS) as PermissionKey[];
